version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    tty: true
    volumes:
      - ./app:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: 'utc'
    ports:
      - 5432:5432
